### ISSUE TITLE
Designer function in runtime

### ISSUE THREAD

**Issue by coolsnake** [RoelBartstra/Designer#6]
Designer is a very good plugin. Thanks. 
Is it possible to port Designer from Editor Mode to Runtime Mode, so that I can start Designer plugin through Blueprint and spawn objects in runtime after I click the play?

**Comment by RoelBartstra** [comment]
This is not the aim for this plugin. If you want to do this in your game it is very easy to setup (even in blueprints). You can take a look at SpawnAssetTool.cpp for more details, but the gist of it is shooting a ray from the mouse position, after hitting something you store the "hit position" and do a line plane intersection. The origin of the plane is the hit position and the normal is the normal of the surface you've hit. The "line" is once again coming from the mouse position.

**Comment by coolsnake** [comment]
Thanks. The next question is the multiple assets selection in run time. This is done in Editor mode. In runtime, I need to list down some assets for plugin to do multiple selection.
